######################################################################
##
## Filename: counter.udo
## Created on: Sun Jun 17 14:27:04 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
