######################################################################
##
## Filename: downsample.udo
## Created on: Sun Jun 17 16:52:24 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
