######################################################################
##
## Filename: phase_band_top.udo
## Created on: Tue Jun 12 8:50:28 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
