######################################################################
##
## Filename: test_tb.udo
## Created on: Mon Jun 11 18:55:22 中国标准时间 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
